### ISSUE TITLE
Packages need to be made for Windows and Linux

### ISSUE THREAD

**Issue by SamCarlberg** [WPIRoboticsProjects/opencv-installer#5]
The only packages I have right now are:

```
opencv-java
opencv-jni-osx-3.1.0
opencv-natives-osx-3.1.0
```

(The headers package is in the works)

**Comment by SamCarlberg** [comment]
linux64 packages were made in 5555159ef9744abc8a3880afd348fbe73111847f

**Comment by JLLeitschuh** [comment]
Use appveyor?

**Comment by SamCarlberg** [comment]
https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.1.0/

**Comment by SamCarlberg** [comment]
Artifacts are being built by FRC Jenkins and are available at http://first.wpi.edu/FRC/roborio/maven
